export enum PostCreationErrorTypes {
  EMPTY_ASSET_IDS_ERROR = 'EXCLUSIVE_POSTS_MUST_HAVE_AT_LEAST_ONE_ASSET',
  NULL_UNLOCK_PRICE_FOR_EXCLUSIVE_POST_ERROR = 'EXCLUSIVE_POSTS_MUST_HAVE_AN_UNLOCK_PRICE_GREATER_THAN_500',
  GENERIC_POST_CREATION_ERROR = 'POST_CREATION_VALIDATION_FAILED',
}
