export enum ProfanityWarningTypes {
  INAPPROPRIATE_USERNAME = 'INAPPROPRIATE_USERNAME_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_BIO = 'INAPPROPRIATE_BIO_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_CAPTION = 'INAPPROPRIATE_CAPTION_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_COMMENT = 'INAPPROPRIATE_COMMENT_MAY_RESULT_IN_PERMANENT_BAN',
}
