export enum ProviderTokens {
  DO_S3_TOKEN = 'DO_S3_TOKEN',
  TYPE_SENSE_TOKEN = 'TYPE_SENSE_TOKEN',
  AWS_S3_TOKEN = 'AWS_S3_TOKEN',
  REQUEST_USER_TOKEN = 'REQUEST_USER_TOKEN',
  REDIS_TOKEN = 'REDIS_TOKEN',
  PLAYWRIGHT_TOKEN = 'PLAYWRIGHT_TOKEN',
  AWS_S3_REQUEST_PRE_SIGNER_TOKEN = 'AWS_S3_REQUEST_PRE_SIGNER_TOKEN',
}
