version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - /
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    versioning-strategy: auto
    labels:
      - dependencies
      - security
    assignees:
      - arijitchhatui
  - package-ecosystem: github-actions
    directories:
      - '/'
    schedule:
      interval: weekly
