export enum ValidationErrorCodes {
  UNIQUE_EMAIL_CONSTRAINT_ERROR = 'UNIQUE_EMAIL_CONSTRAINT_ERROR',
  UNIQUE_USERNAME_CONSTRAINT_ERROR = 'UNIQUE_USERNAME_CONSTRAINT_ERROR',
}

export enum ProfanityWarningTypes {
  INAPPROPRIATE_USERNAME = 'INAPPROPRIATE_USERNAME_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_BIO = 'INAPPROPRIATE_BIO_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_CAPTION = 'INAPPROPRIATE_CAPTION_MAY_RESULT_IN_PERMANENT_BAN',
}

export enum GraphqlErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
