export enum ValidationErrorCodes {
  UNIQUE_EMAIL_CONSTRAINT_ERROR = 'UNIQUE_EMAIL_CONSTRAINT_ERROR',
  UNIQUE_USERNAME_CONSTRAINT_ERROR = 'UNIQUE_USERNAME_CONSTRAINT_ERROR',
}

export enum ProfanityWarningTypes {
  INAPPROPRIATE_USERNAME = 'INAPPROPRIATE_USERNAME_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_BIO = 'INAPPROPRIATE_BIO_MAY_RESULT_IN_PERMANENT_BAN',
  INAPPROPRIATE_CAPTION = 'INAPPROPRIATE_CAPTION_MAY_RESULT_IN_PERMANENT_BAN',
}

export enum GraphqlErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export enum PostCreationErrorTypes {
  EMPTY_ASSET_IDS_ERROR = 'EXCLUSIVE_POSTS_MUST_HAVE_AT_LEAST_ONE_ASSET',
  NULL_UNLOCK_PRICE_FOR_EXCLUSIVE_POST_ERROR = 'EXCLUSIVE_POSTS_MUST_HAVE_AN_UNLOCK_PRICE_GREATER_THAN_500',
  GENERIC_POST_CREATION_ERROR = 'POST_CREATION_VALIDATION_FAILED',
}
