name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Packages
        run: npm install

      - name: Lint Check
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test Docker build
        run: docker build . -t app:latest
