name: Deploy

on:
 push:
   branches: [main]

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   environment: production
   steps:
     - name: Checkout repository
       uses: actions/checkout@v5
       
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         app_name: meowfans-service
