name: Release Workflow

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Push to prod branch
        run: |
         git push origin --delete deploy || true
         git checkout -b deploy
         git push origin deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
